SystemRepairWeb/Models/Repair.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SystemRepairWeb.Models
{
    /// <summary>
    /// Ремонт
    /// </summary>
    public class Repair
    {
        /// <summary>
        /// Идентификатор
        /// </summary>
        [Key]
        public int RepairID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Дата начала")]
        public DateTime DateStart { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Дата окончания")]
        public DateTime DateFinish { get; set; }
        public int MachineID { get; set; }
        /// <summary>
        /// Ремонтируемое оборудование
        /// </summary>
        public virtual Machine Machine { get; set; }
        public int TypeOfRepairID { get; set; }
        /// <summary>
        /// Тип ремонта
        /// </summary>
        public virtual TypeOfRepair Type { get; set; }

        //TODO: придумать, как привязать, или отвязать полностью
        public int? MonthlyAllotmentID { get; set; }
        public virtual MonthlyAllotment Month { get; set; }
        /// <summary>
        /// Примечание
        /// </summary>
        [StringLength(300)]
        public string Note { get; set; }
        /// <summary>
        /// Использованные масла
        /// </summary>
        public virtual ICollection<RepairOil> Oils { get; set; }
        /// <summary>
        /// Использованные СОЖ
        /// </summary>
        public virtual ICollection<RepairCoolant> Coolants { get; set; }
        /// <summary>
        /// Использованные запчасти
        /// </summary>
        public virtual ICollection<RepairSparePart> SpareParts { get; set; }
    }
}

SystemRepairWeb/Controllers/RepairsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SystemRepairWeb.Models;

namespace SystemRepairWeb.Controllers
{
    public class RepairsController : Controller
    {
        private readonly ApplicationContext _context;

        public RepairsController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Repairs
        public async Task<IActionResult> Index(string typeOfRepair,string workshop, string searchString, DateTime? startDate, DateTime? endDate )
        {
            IQueryable<string> typesRepairQuery = from m in _context.Repairs
                orderby m.Type.Name
                select m.Type.Name;
            IQueryable<string> workshopQuery = from w in _context.Workshops
                orderby w.WorkshopNameNumber
                select w.WorkshopNameNumber;
                 var repairs = from s in _context.Repairs
            select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                try
                {
                    repairs = repairs.Where(s =>
                            s.Machine.InventoryNumber.Contains(searchString)
                            || s.Type.Name.Contains(searchString)
                            || s.DateStart.ToString("{0:yyyy-MM-dd}").Contains(searchString)
                            || s.DateFinish.ToString("{0:yyyy-MM-dd}").Contains(searchString)
                    );
                }
                catch
                {

                }
            }

            if (!string.IsNullOrEmpty(typeOfRepair))
            {
                repairs = repairs.Where(x => x.Type.Name == typeOfRepair);
            }

            if (!String.IsNullOrEmpty(workshop))
            {
                repairs = repairs.Where(o => o.Machine.Workshop.WorkshopNameNumber == workshop);
            }
            if (startDate != null && endDate != null && (startDate <= endDate || endDate==DateTime.MinValue))
            {
                repairs = repairs.Where(r => (r.DateStart >= startDate )
                                             && ( r.DateStart <= endDate));
            }
            else
            if (startDate != null)
            {
                
                repairs = repairs.Where(y => y.DateStart >= startDate );
            }
            else
            if (endDate != null)
            {
                repairs = repairs.Where(z => z.DateStart<=endDate);
            }
            var typeRepairVM = new RepairTypeViewModel
            {
                Types = new SelectList(await typesRepairQuery.Distinct().ToListAsync()),
                Workshops = new SelectList(await workshopQuery.Distinct().ToListAsync()),
                Repairs = await repairs.ToListAsync()
            };
            return View(typeRepairVM);
        }

        // GET: Repairs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var repair = await _context.Repairs
                .FirstOrDefaultAsync(m => m.RepairID == id);
            if (repair == null)
            {
                return NotFound();
            }

            return View(repair);
        }

        // GET: Repairs/Create
        public IActionResult Create()
        {
            ViewData["MachineID"] = new SelectList(_context.Machines, "MachineID", "NameNumber");
            ViewData["TypeOfRepairID"] = new SelectList(_context.TypeOfRepair, "TypeOfRepairID", "Name");
            return View();
        }

        // POST: Repairs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RepairID,DateStart,DateFinish,MachineID,TypeOfRepairID,Note")] Repair repair)
        {
            if (ModelState.IsValid)
            {
                MonthlyAllotment monthlyAllotment = await _context.MonthlyAllotment
                    .FirstOrDefaultAsync(ma => ma.Month.Month == repair.DateStart.Month
                                               && ma.Month.Year == repair.DateStart.Year);
                if (monthlyAllotment != null)
                {
                    repair.MonthlyAllotmentID = monthlyAllotment.MonthlyAllotmentID;
                    repair.Month = monthlyAllotment;
                }
                _context.Add(repair);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MachineID"] = new SelectList(_context.Machines, "MachineID", "NameNumber", repair.MachineID);
            ViewData["TypeOfRepairID"] = new SelectList(_context.TypeOfRepair, "TypeOfRepairID", "Name", repair.TypeOfRepairID);
            return View(repair);
        }

        // GET: Repairs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var repair = await _context.Repairs.FindAsync(id);
            if (repair == null)
            {
                return NotFound();
            }
            ViewData["MachineID"] = new SelectList(_context.Machines, "MachineID", "NameNumber", repair.MachineID);
            ViewData["TypeOfRepairID"] = new SelectList(_context.TypeOfRepair, "TypeOfRepairID", "Name", repair.TypeOfRepairID);
            return View(repair);
        }

        // POST: Repairs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RepairID,DateStart,DateFinish,MachineID,TypeOfRepairID,Note")] Repair repair)
        {
            if (id != repair.RepairID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    MonthlyAllotment monthlyAllotment = await _context.MonthlyAllotment
                        .FirstOrDefaultAsync(ma => ma.Month.Month == repair.DateStart.Month
                                                   && ma.Month.Year == repair.DateStart.Year);
                    if (monthlyAllotment != null)
                    {
                        repair.MonthlyAllotmentID = monthlyAllotment.MonthlyAllotmentID;
                        repair.Month = monthlyAllotment;
                    }

                    _context.Update(repair);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RepairExists(repair.RepairID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MachineID"] = new SelectList(_context.Machines, "MachineID", "NameNumber", repair.MachineID);
            ViewData["TypeOfRepairID"] = new SelectList(_context.TypeOfRepair, "TypeOfRepairID", "Name", repair.TypeOfRepairID);
            return View(repair);
        }

        // GET: Repairs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var repair = await _context.Repairs
                .FirstOrDefaultAsync(m => m.RepairID == id);
            if (repair == null)
            {
                return NotFound();
            }

            return View(repair);
        }

        // POST: Repairs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var repair = await _context.Repairs.FindAsync(id);
            _context.Repairs.Remove(repair);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        public IActionResult AddSparePart()
        {
            ViewData["RepairID"] = new SelectList(_context.Repairs, "RepairID", "RepairID");
            ViewData["SparePartID"] = new SelectList(_context.SpareParts, "SparePartID", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSparePart([Bind("RepairID,SparePartID")] RepairSparePart repairSparePart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(repairSparePart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), repairSparePart.Repair.RepairID);
            }
            ViewData["RepairID"] = new SelectList(_context.Repairs, "RepairID", "RepairID", repairSparePart.Repair.RepairID);
            ViewData["SparePartID"] = new SelectList(_context.SpareParts, "SparePartID", "Name", repairSparePart.SparePart.SparePartID);
            return View(repairSparePart);
        }

        private bool RepairExists(int id)
        {
            return _context.Repairs.Any(e => e.RepairID == id);
        }
    }
}

SystemRepairWeb/Views/Repairs/AddSparePart.cshtml
@model SystemRepairWeb.Models.RepairSparePart
@{
    ViewData["Title"] = "Добавить запчасть";
}

<h2>Добавить к ремонту</h2>

<h4>Запчасть</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Repairs" asp-action="AddSparePart">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RepairID" class="control-label">Ремонт</label>
                <select asp-for="RepairID" class="form-control" asp-items="ViewBag.RepairID"></select>
            </div>
            <div class="form-group">
                <label asp-for="SparePartID" class="control-label">Запчасть</label>
                <select asp-for="SparePartID" class="form-control" asp-items="ViewBag.SparePartID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<div>
    <a class="btn btn-info" asp-action="Details">К ремонту</a>
</div>

SystemRepairWeb/Views/Repairs/Create.cshtml
@model SystemRepairWeb.Models.Repair

@{
    ViewData["Title"] = "Добавить ремонт";
}

<h2>Добавить</h2>

<h4>Ремонт</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateStart" class="control-label">Дата начала</label>
                <input asp-for="DateStart" class="form-control" />
                <span asp-validation-for="DateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFinish" class="control-label">Дата окончания</label>
                <input asp-for="DateFinish" class="form-control" />
                <span asp-validation-for="DateFinish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MachineID" class="control-label">Оборудование</label>
                <select asp-for="MachineID" class ="form-control" asp-items="ViewBag.MachineID"></select>
            </div>
            <div class="form-group">
                <label asp-for="TypeOfRepairID" class="control-label">Тип ремонта</label>
                <select asp-for="TypeOfRepairID" class ="form-control" asp-items="ViewBag.TypeOfRepairID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label">Описание</label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-default" asp-action="Index">К общему списку</a>
</div>

SystemRepairWeb/Views/Repairs/Delete.cshtml
@model SystemRepairWeb.Models.Repair

@{
    ViewData["Title"] = "Удалить ремонт";
}

<h2>Удаление</h2>

<h3>Подтверждаете удаление?</h3>
<div>
    <h4>Ремонт</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Дата начала
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateStart)
        </dd>
        <dt>
           Дата окончания
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateFinish)
        </dd>
        <dt>
            Оборудование
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Machine.MachineID)
        </dd>
        <dt>
            Тип ремонта
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>
        <dt>
            Описание
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RepairID" />
        <input class="btn btn-danger" type="submit" value="Удалить"/> |
        <a class="btn btn-default" asp-action="Index">К общему списку</a>
    </form>
</div>

SystemRepairWeb/Views/Repairs/Details.cshtml
@model SystemRepairWeb.Models.Repair

@{
    ViewData["Title"] = "Ремонт";
}

<h2>Информация</h2>

<div>
    <h4>Ремонт</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Дата начала
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateStart)
        </dd>
        <dt>
            Дата окончания
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateFinish)
        </dd>
        <dt>
            Оборудование
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Machine.NameNumber)
        </dd>
        <dt>
            Тип ремонта
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>
        <dt>
            Описание
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dd>
            <a asp-controller="Repairs" asp-action="AddSparePart" asp-route-id="@Model.RepairID">Добавить запчасть</a>
        </dd>
    </dl>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Название
                </th>

                <th>
                    <!--<input type="hidden" asp-for="RepairID" />-->
                    
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.SpareParts)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SparePart.Name)
                </td>
                <td>
                     |
                    <a asp-controller="SpareParts" class="btn btn-info" asp-action="Details" asp-route-id="@item.SparePart.SparePartID">Подробнее</a> |
                    <!--<a asp-controller="Repairs" asp-action="DeleteSparePart" asp-route-id="@item.SparePart.SparePartID">Удалить</a>-->
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.RepairID">Изменить</a> |
    <a class="btn btn-default" asp-action="Index">К общему списку</a>
</div>

SystemRepairWeb/Views/Repairs/Edit.cshtml
@model SystemRepairWeb.Models.Repair

@{
    ViewData["Title"] = "Изменить ремонт";
}

<h2>Редактирование</h2>

<h4>Ремонт</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RepairID" />
            <div class="form-group">
                <label asp-for="DateStart" class="control-label">Дата начала</label>
                <input asp-for="DateStart" class="form-control" />
                <span asp-validation-for="DateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFinish" class="control-label">Дата окончания</label>
                <input asp-for="DateFinish" class="form-control" />
                <span asp-validation-for="DateFinish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MachineID" class="control-label">Оборудование</label>
                <select asp-for="MachineID" class="form-control" asp-items="ViewBag.MachineID"></select>
                <span asp-validation-for="MachineID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeOfRepairID" class="control-label">Тип ремонта</label>
                <select asp-for="TypeOfRepairID" class="form-control" asp-items="ViewBag.TypeOfRepairID"></select>
                <span asp-validation-for="TypeOfRepairID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label">Описание</label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-default" asp-action="Index">К общему списку</a>
</div>

SystemRepairWeb/Views/Repairs/Index.cshtml
@model SystemRepairWeb.Models.RepairTypeViewModel

@{
    ViewData["Title"] = "Ремонты";
}

<h2>Ремонты</h2>

<p>
    <a class="btn btn-success" asp-action="Create">Добавить новый</a>
</p>
<form asp-controller="Repairs" asp-action="Index">
    <p>
        Поиск: <input type="text" name="SearchString">
        Тип: <select asp-for="TypeOfRepair" asp-items="Model.Types">
            <option value="">Все</option>
        </select>
        Цех: <select asp-for="Workshop" asp-items="Model.Workshops">
            <option value="">Все</option>
        </select>

        Начало: <input type="date" name="startDate" placeholder="С" />
        Окончание: <input type="date" name="endDate" placeholder="До" />
        <!--<div class="form-group">
                    <label class="control-label">Дата начала</label>
                    class="form-control"
                    <span class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Дата окончания</label>
    class="form-control"
                    <span class="text-danger"></span>
                </div>-->


        <input type="submit" value="Найти" />
    </p>
        </form>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Дата начала
                    </th>
                    <th>
                        Дата окончания
                    </th>
                    <th>
                        Оборудование
                    </th>
                    <th>
                        Тип ремонта
                    </th>
                    <th>
                        Описание
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model.Repairs) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateStart)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateFinish)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Machine.NameNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Note)
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.RepairID">Изменить</a> |
                        <a class="btn btn-info" asp-action="Details" asp-route-id="@item.RepairID">Подробнее</a> |
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.RepairID">Удалить</a>
                    </td>
                </tr>
        }
            </tbody>
        </table>

SystemRepairWeb/Views/Repairs/RepairabilityList.cshtml
@{
    ViewData["Title"] = "RepairabilityList";
}

<h2>RepairabilityList</h2>