SystemRepairWeb/Models/ModelOfMachine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;
namespace SystemRepairWeb.Models
{
    /// <summary>
    /// Модель оборудования
    /// </summary>
    public class ModelOfMachine
    {
        [Key]
        [Required]
        public int ModelOfMachineID { get; set; }
        /// <summary>
        /// Название
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        public int TypeOfMachineID { get; set; }
        /// <summary>
        /// Тип оборудования
        /// </summary>
      //  [Required]
        public virtual TypeOfMachine Type { get; set; }
        /// <summary>
        /// Модель ЧПУ
        /// </summary>
        public string ModelCNC { get; set; }
        /// <summary>
        /// Ремонтосложность
        /// </summary>
        public float Repairability { get; set; }
        /// <summary>
        /// Страна производитель
        /// </summary>
        [StringLength(50)]
        public string Country { get; set; }

        public virtual ICollection<Machine> Machines { get; set; }
    }
}

SystemRepairWeb/Models/ModelOfMachineViewModel.cs
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace SystemRepairWeb.Models
{
    public class ModelOfMachineViewModel
    {

        public List<ModelOfMachine> Models { get; set; }
        public SelectList Types { get; set; }
        public string TypeOfMachine { get; set; }
        public string SearchString { get; set; }

        public SelectList Countries { get; set; }
        public string Country { get; set; }
    }
}

SystemRepairWeb/Controllers/ModelOfMachinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SystemRepairWeb.Models;

namespace SystemRepairWeb.Controllers
{
    public class ModelOfMachinesController : Controller
    {
        private readonly ApplicationContext _context;

        public ModelOfMachinesController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: ModelOfMachines
        public async Task<IActionResult> Index(string searchString, string CNCcontrol)
        {
            var models = from m in _context.ModelOfMachines//.Include(m => m.Type)
                                    // orderby m.Type.Name
                select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                try
                {
                    models = models.Where(s =>
                        s.Type.Name.Contains(searchString)
                        || s.Name.Contains(searchString));
                }
                catch
                {

                }
            }
            if (!String.IsNullOrEmpty(CNCcontrol))
            {
                switch (CNCcontrol)
                {
                    case "Есть":
                    {
                        models = models.Where(s => !String.IsNullOrEmpty(s.ModelCNC));
                        break;
                    }

                    case "Нет":
                    {
                        models = models.Where(s => String.IsNullOrEmpty(s.ModelCNC));
                        break;
                    }

                    case "Все":
                    {
                        models = models.Where(s => String.IsNullOrEmpty(s.ModelCNC)|| !String.IsNullOrEmpty(s.ModelCNC));
                        break;
                    }
                }
            }
            return View(await models.ToListAsync());
        }

        // GET: ModelOfMachines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelOfMachine = await _context.ModelOfMachines
                //.Include(m => m.Type)
                //.Include(m => m.Machines)
                .FirstOrDefaultAsync(m => m.ModelOfMachineID == id);

            if (modelOfMachine == null)
            {
                return NotFound();
            }

            return View(modelOfMachine);
        }

        // GET: ModelOfMachines/Create
        public IActionResult Create()
        {
            ViewData["TypeOfMachineID"] = new SelectList(_context.TypeOfMachines, "TypeOfMachineID", "Name");
            return View();
        }

        // POST: ModelOfMachines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ModelOfMachineID,Name,TypeOfMachineID,ModelCNC,Repairability,Country")] ModelOfMachine modelOfMachine)
        {
            if (ModelState.IsValid)
            {
                _context.Add(modelOfMachine);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TypeOfMachineID"] = new SelectList(_context.TypeOfMachines, "TypeOfMachineID", "Name", modelOfMachine.TypeOfMachineID);
            return View(modelOfMachine);
        }

        // GET: ModelOfMachines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelOfMachine = await _context.ModelOfMachines.FindAsync(id);
            if (modelOfMachine == null)
            {
                return NotFound();
            }
            ViewData["TypeOfMachineID"] = new SelectList(_context.TypeOfMachines, "TypeOfMachineID", "Name", modelOfMachine.TypeOfMachineID);
            return View(modelOfMachine);
        }

        // POST: ModelOfMachines/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ModelOfMachineID,Name,TypeOfMachineID,ModelCNC,Repairability,Country")] ModelOfMachine modelOfMachine)
        {
            if (id != modelOfMachine.ModelOfMachineID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(modelOfMachine);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModelOfMachineExists(modelOfMachine.ModelOfMachineID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TypeOfMachineID"] = new SelectList(_context.TypeOfMachines, "TypeOfMachineID", "Name", modelOfMachine.TypeOfMachineID);
            return View(modelOfMachine);
        }

        // GET: ModelOfMachines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelOfMachine = await _context.ModelOfMachines
                //.Include(m => m.Type)
                .FirstOrDefaultAsync(m => m.ModelOfMachineID == id);
            if (modelOfMachine == null)
            {
                return NotFound();
            }

            return View(modelOfMachine);
        }

        // POST: ModelOfMachines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var modelOfMachine = await _context.ModelOfMachines.FindAsync(id);
            _context.ModelOfMachines.Remove(modelOfMachine);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModelOfMachineExists(int id)
        {
            return _context.ModelOfMachines.Any(e => e.ModelOfMachineID == id);
        }
    }
}

SystemRepairWeb/Views/ModelOfMachines/Create.cshtml
@model SystemRepairWeb.Models.ModelOfMachine

@{
    ViewData["Title"] = "Добавить модель";
}

<h2>Добавить</h2>

<h4>Модель оборудования</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeOfMachineID" class="control-label">Тип</label>
                <select asp-for="TypeOfMachineID" class ="form-control" asp-items="ViewBag.TypeOfMachineID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ModelCNC" class="control-label">Модель ЧПУ</label>
                <input asp-for="ModelCNC" class="form-control" />
                <span asp-validation-for="ModelCNC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Repairability" class="control-label">Ремонтосложность</label>
                <input asp-for="Repairability" class="form-control" />
                <span asp-validation-for="Repairability" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label">Страна-изготовитель</label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-default" asp-action="Index">К общему списку</a>
</div>

SystemRepairWeb/Views/ModelOfMachines/Delete.cshtml
@model SystemRepairWeb.Models.ModelOfMachine

@{
    ViewData["Title"] = "Удалить модель";
}

<h2>Удаление</h2>

<h3>Подтверждаете удаление?</h3>
<div>
    <h4>Модель оборудования</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Название
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Тип
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>
        <dt>
            Модель ЧПУ
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModelCNC)
        </dd>
        <dt>
            Ремонтосложность
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Repairability)
        </dd>
        <dt>
            Страна-изготовитель
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ModelOfMachineID" />
        <input class="btn btn-danger" type="submit" value="Удалить"/> |
        <a class="btn btn-default" asp-action="Index">К общему списку</a>
    </form>
</div>

SystemRepairWeb/Views/ModelOfMachines/Details.cshtml
@model SystemRepairWeb.Models.ModelOfMachine

@{
    ViewData["Title"] = "Модель оборудования";
}

<h2>Информация</h2>

<div>
    <h4>Модель оборудования</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Название
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Тип
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>
        <dt>
            Модель ЧПУ
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModelCNC)
        </dd>
        <dt>
            Ремонтосложность
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Repairability)
        </dd>
        <dt>
            Страна-изготовитель
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dd>
            <a asp-controller="Machines" asp-action="Create">Добавить экземпляр</a>
        </dd>
    </dl>
    <table class="table">
        <thead>
        <tr>
            <th>
                Модель
            </th>
            <th>
                Цех
            </th>
            <th>
                Инвентарный номер
            </th>
            <th>
                Дата ввода в эксплуатацию
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.Machines) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Model.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Workshop.WorkshopNameNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InventoryNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateStart)
                </td>
                <td>
                    <a asp-controller="Machines" class="btn btn-primary" asp-action="Edit" asp-route-id="@item.MachineID">Изменить</a> |
                    <a asp-controller="Machines" class="btn btn-info" asp-action="Details" asp-route-id="@item.MachineID">Подробнее</a> |
                    <a asp-controller="Machines" class="btn btn-danger" asp-action="Delete" asp-route-id="@item.MachineID">Удалить</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.ModelOfMachineID">Изменить</a> |
    <a class="btn btn-default" asp-action="Index">К общему списку</a>
</div>

SystemRepairWeb/Views/ModelOfMachines/Edit.cshtml
@model SystemRepairWeb.Models.ModelOfMachine

@{
    ViewData["Title"] = "Изменить модель";
}

<h2>Редактирование</h2>

<h4>Модель оборудования</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ModelOfMachineID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeOfMachineID" class="control-label">Тип</label>
                <select asp-for="TypeOfMachineID" class="form-control" asp-items="ViewBag.TypeOfMachineID"></select>
                <span asp-validation-for="TypeOfMachineID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelCNC" class="control-label">Модель ЧПУ</label>
                <input asp-for="ModelCNC" class="form-control" />
                <span asp-validation-for="ModelCNC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Repairability" class="control-label">Ремонтосложность</label>
                <input asp-for="Repairability" class="form-control" />
                <span asp-validation-for="Repairability" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label">Страна-изготовитель</label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-default" asp-action="Index">К общему списку</a>
</div>

SystemRepairWeb/Views/ModelOfMachines/Index.cshtml
<!--<!doctype html>
<html lang="ru">
<head>-->
<!-- Required meta tags 
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
-->
<!-- Bootstrap CSS
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
-->
@model IEnumerable<SystemRepairWeb.Models.ModelOfMachine>

@{
    ViewData["Title"] = "Модели оборудования";
}
<!--</head>
<body>-->
<h2>Модели оборудования</h2>

<p>
    <a class="btn btn-success" asp-action="Create">Добавить новую</a>
</p>
<form asp-controller="ModelOfMachines" asp-action="Index">
    <p>
        Поиск: <input type="text" name="SearchString">
        <!--<select asp-for="TypeOfMachine" asp-items="Model.Types">
            <option value="">Все</option>
        </select>
        <select asp-for="Country" asp-items="Model.Countries">
            <option value="">Все</option>
        </select>-->
        <select size="1" name="CNCcontrol">
            <option disabled>Наличие ЧПУ</option>
            <option value="Все">Все</option>
            <option value="Нет">Нет ЧПУ</option>
            <option value="Есть">Есть ЧПУ</option>
        </select>
        <input type="submit" value="Найти" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Модель
            </th>
            <th>
                Тип
            </th>
            <th>
                Модель ЧПУ
            </th>
            <th>
                Ремонтосложность
            </th>
            <th>
                Страна-изготовитель
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModelCNC)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Repairability)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.ModelOfMachineID">Изменить</a> |
                    <a class="btn btn-info" asp-action="Details" asp-route-id="@item.ModelOfMachineID">Подробнее</a> |
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.ModelOfMachineID">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>-->